### ISSUE TITLE
Enable tag search in editor after typing `#`

### ISSUE THREAD

**Issue by guoliu** [thematters/matters-editor#192]
**Is your feature request related to a problem? Please describe.**
Currently an user can type `@` in editor and enable user search and selection. As tag become more important, an user should also be able to type `#` in editor and enable tag search and selection

**Describe the solution you'd like**
When an user type `#` and some content in editor, a dropdown of tags should appear according to the content the user typed, allowing the user to select which tag s/he would like to mention. This should be similar with typing `@` for an user.

**Additional context**
Currently the editor API only support mentioning user, see [example here](https://github.com/thematters/matters-web/blob/develop/src/components/Editor/Article/index.tsx#L52). We need to either add mention tag to the API, or generalize to any type of mentioning.

**Comment by mayyyc** [comment]
@guoliu I'm thinking something like this
```
<MattersArticleEditor
          editorContent={content || ''}
          editorContentId={id}
          editorUpdate={update}
          editorUpload={upload}
          eventName={ADD_TOAST}
          language={lang.toUpperCase()}
          mentionLoading={loading}
          mentionKeywordChange={mentionKeywordChange}
          mentionUsers={mentionUsers}
          mentionListComponent={MentionUserList}
          **mentionTags={mentionTags}
          mentionTagListComponent={MentionTagList}
          mentionTagLoading={tagLoading}
          mentionTagKeywordChange={mentionTagKeywordChange}**
          readOnly={readyOnly}
          siteDomain="matters.news"
          theme="bubble"
          titleDefaultValue={title || ''}
          uploadAssetDomain={process.env.NEXT_PUBLIC_ASSET_DOMAIN || ''}
        />
```

on the editor side, I'm looking at ```src/modules/mention.ts``` and thinking extend it to make it work for tags as well. 

Let me know if you have any suggestions on the API or if I'm on the right path.

I've been struggling a little bit understanding Quill last weekend, but I've set aside my today for this issue so hopefully i can figure something out. I'm really keen on this =)

**Comment by robertu7** [comment]
Hi @mayyyc, Thanks for diving into this repo! 

I'm refactoring this repo and plan to remove `mention*` props. Here are some backgrounds:

In [this PR](https://github.com/thematters/matters-web/pull/1440), we added a new component called `<SearchSelectDialoag>`, to search & select nodes, which can be used by `#` (add a tag) and `@` (mention a user). 

While typing `@` or `#`, instead of showing the `mentionListComponent` inside the [`<Mention>` ](https://github.com/thematters/matters-editor/blob/develop/src/components/Mention/index.tsx) of `matters-editor`, we will show the `<SearchSelectDialoag>` outside of it. I expect this move will make the API cleaner. 

Feel free to comment if you have any ideas!

**Comment by mayyyc** [comment]
@robertu7 so all the mentionLoading/mentionUsers/mentionListComponent will be handled outside the editor? and we only listen to @ or # in the editor and show <SearchSelectDialog />?

That sounds like a nice and clean solution, I like it. I'll look into the implementation of mention module a little more and keep this in mind.

Thanks for the update.

**Comment by robertu7** [comment]
@mayyyc Yes! that's what I thought. 

Since what I am working on could block the development of `#`, let's figure out how the workflow would be:

For mention user (`@`) refactoring, I have pushed a [commit](https://github.com/thematters/matters-editor/pull/195) as the first step, next will be working on [`src/modules/mention`](https://github.com/thematters/matters-editor/blob/develop/src/modules/mention.ts), to handle the typing, showing, inserting logics. (@robertu7 working in progress)

For tag adding (`#`) feature of this issue, we can make a [blot](https://github.com/thematters/matters-editor/blob/develop/src/blots/Mention.ts) first, then the module. (@mayyyc  feel free to pick if you like :D)

**Comment by mayyyc** [comment]
@robertu7 how is your progress on modules/mention? I'm thinking it will handle tag as well, is that right? 

If you haven't started, i might give it a go.

**Comment by robertu7** [comment]
@mayyyc We are working on other features, so https://github.com/thematters/matters-editor/pull/195 may not have any commit during the next few weeks. Please feel free to take it, thanks a lot!

BTW, https://github.com/thematters/matters-web/pull/1440 has already been deployed to production, currently used by 「添加精選作品」and「添加我的作品」in tag detail page, you might have a try.
